apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller
spec:
  selector:
    matchLabels:
      app: caller
      tier: app
  template:
    metadata:
      labels:
        app: caller
        tier: app
    spec:
      containers:
        - name: caller
          image: dhsimpson/sample-caller:amd