apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: responder
          image: dhsimpson/sample-ingress:hello
          ports:
            - containerPort: 12345
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  ports:
    - port: 12222
      protocol: TCP
      targetPort: 12345
      protocol: TCP
  selector:
    app: app